version: '3.9'
services:
    httpd:
        build:
          context: .
          dockerfile: httpd.dockerfile
        restart: always
        ports:
          - 80:80
        volumes:
          - ./wordpress:/var/www/html
        depends_on:
          - php
          - mysql
    mysql:
        build:
            context: .
            dockerfile: mysql.dockerfile
        restart: always
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        restart: always
        volumes:
            - ./wordpress:/var/www/html
    wp:
        image: wordpress:cli-php8.0
        depends_on:
            - php
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: 'wp'
            WORDPRESS_DB_NAME: 'wp'
            WORDPRESS_DB_PASSWORD: 'secret'
            WORDPRESS_DEBUG: '1'
            WP_ALLOW_MULTISITE: 'true'
        volumes:
            - ./wordpress:/var/www/html